name: "Publish latest blog post"
on: 
    schedule:
        - cron: '30 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: aei-tech/blogpost-workflow@main
              with: 
                max_post_count: "4"
                feed_list: "https://blog.aei-te.ch/feed/"
